version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/node"
    versions:
    - 6.2.5
    - 6.3.0
    - 6.3.1
    - 6.3.2
  - dependency-name: "@sentry/browser"
    versions:
    - 6.2.5
    - 6.3.0
    - 6.3.1
    - 6.3.2
  - dependency-name: framer-motion
    versions:
    - 4.1.10
    - 4.1.2
    - 4.1.3
    - 4.1.5
    - 4.1.6
    - 4.1.8
    - 4.1.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@chakra-ui/react"
    versions:
    - 1.4.2
    - 1.5.0
    - 1.5.1
    - 1.5.2
  - dependency-name: release-it
    versions:
    - 14.5.1
    - 14.6.0
  - dependency-name: "@sentry/webpack-plugin"
    versions:
    - 1.15.0
  - dependency-name: next
    versions:
    - 10.1.3
